volumes:
    postgres-data:
    pg-admin:
        external: true
services:
    fastapi:
        environment:
            CORS_HOST: http://localhost:5173
            DATABASE_URL: postgresql://example_user:secret@postgres/example_db
            SIGNING_KEY: ${SIGNING_KEY_ENV_VAR}
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./api:/app
    pg-admin:
        image: dpage/pgadmin4
        volumes:
            - pg-admin:/var/lib/pgadmin
        ports:
            - 8082:80
        environment:
            PGADMIN_DEFAULT_EMAIL: CyberMavericks@gmail.com
            PGADMIN_DEFAULT_PASSWORD: CyberMavericks
            PGADMIN_DISABLE_POSTFIX: 1

    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./ghi:/app
        ports:
            - "5173:5173"
    postgres:
        image: postgres:14.5-bullseye
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: example_user
            POSTGRES_DB: example_db
        ports:
            - 15432:5432
